export const NATIONALITIES = [
  { value: 'UAE', label: 'الإمارات العربية المتحدة | United Arab Emirates' },
  { value: 'AFG', label: 'أفغانستان | Afghanistan' },
  { value: 'ALB', label: 'ألبانيا | Albania' },
  { value: 'DZA', label: 'الجزائر | Algeria' },
  { value: 'AND', label: 'أندورا | Andorra' },
  { value: 'AGO', label: 'أنغولا | Angola' },
  { value: 'ARG', label: 'الأرجنتين | Argentina' },
  { value: 'ARM', label: 'أرمينيا | Armenia' },
  { value: 'AUS', label: 'أستراليا | Australia' },
  { value: 'AUT', label: 'النمسا | Austria' },
  { value: 'AZE', label: 'أذربيجان | Azerbaijan' },
  { value: 'BHR', label: 'البحرين | Bahrain' },
  { value: 'BGD', label: 'بنغلاديش | Bangladesh' },
  { value: 'BRB', label: 'بربادوس | Barbados' },
  { value: 'BLR', label: 'بيلاروسيا | Belarus' },
  { value: 'BEL', label: 'بلجيكا | Belgium' },
  { value: 'BLZ', label: 'بليز | Belize' },
  { value: 'BEN', label: 'بنين | Benin' },
  { value: 'BTN', label: 'بوتان | Bhutan' },
  { value: 'BOL', label: 'بوليفيا | Bolivia' },
  { value: 'BIH', label: 'البوسنة والهرسك | Bosnia and Herzegovina' },
  { value: 'BWA', label: 'بوتسوانا | Botswana' },
  { value: 'BRA', label: 'البرازيل | Brazil' },
  { value: 'BRN', label: 'بروناي | Brunei' },
  { value: 'BGR', label: 'بلغاريا | Bulgaria' },
  { value: 'BFA', label: 'بوركينا فاسو | Burkina Faso' },
  { value: 'BDI', label: 'بوروندي | Burundi' },
  { value: 'KHM', label: 'كمبوديا | Cambodia' },
  { value: 'CMR', label: 'الكاميرون | Cameroon' },
  { value: 'CAN', label: 'كندا | Canada' },
  { value: 'CPV', label: 'الرأس الأخضر | Cape Verde' },
  { value: 'CAF', label: 'جمهورية أفريقيا الوسطى | Central African Republic' },
  { value: 'TCD', label: 'تشاد | Chad' },
  { value: 'CHL', label: 'تشيلي | Chile' },
  { value: 'CHN', label: 'الصين | China' },
  { value: 'COL', label: 'كولومبيا | Colombia' },
  { value: 'COM', label: 'جزر القمر | Comoros' },
  { value: 'COG', label: 'الكونغو | Congo' },
  { value: 'CRI', label: 'كوستاريكا | Costa Rica' },
  { value: 'HRV', label: 'كرواتيا | Croatia' },
  { value: 'CUB', label: 'كوبا | Cuba' },
  { value: 'CYP', label: 'قبرص | Cyprus' },
  { value: 'CZE', label: 'جمهورية التشيك | Czech Republic' },
  { value: 'DNK', label: 'الدانمارك | Denmark' },
  { value: 'DJI', label: 'جيبوتي | Djibouti' },
  { value: 'DMA', label: 'دومينيكا | Dominica' },
  { value: 'DOM', label: 'جمهورية الدومينيكان | Dominican Republic' },
  { value: 'ECU', label: 'الإكوادور | Ecuador' },
  { value: 'EGY', label: 'مصر | Egypt' },
  { value: 'SLV', label: 'السلفادور | El Salvador' },
  { value: 'GNQ', label: 'غينيا الاستوائية | Equatorial Guinea' },
  { value: 'ERI', label: 'إريتريا | Eritrea' },
  { value: 'EST', label: 'إستونيا | Estonia' },
  { value: 'ETH', label: 'إثيوبيا | Ethiopia' },
  { value: 'FJI', label: 'فيجي | Fiji' },
  { value: 'FIN', label: 'فنلندا | Finland' },
  { value: 'FRA', label: 'فرنسا | France' },
  { value: 'GAB', label: 'الغابون | Gabon' },
  { value: 'GMB', label: 'غامبيا | Gambia' },
  { value: 'GEO', label: 'جورجيا | Georgia' },
  { value: 'DEU', label: 'ألمانيا | Germany' },
  { value: 'GHA', label: 'غانا | Ghana' },
  { value: 'GRC', label: 'اليونان | Greece' },
  { value: 'GRD', label: 'غرينادا | Grenada' },
  { value: 'GTM', label: 'غواتيمالا | Guatemala' },
  { value: 'GIN', label: 'غينيا | Guinea' },
  { value: 'GNB', label: 'غينيا بيساو | Guinea-Bissau' },
  { value: 'GUY', label: 'غويانا | Guyana' },
  { value: 'HTI', label: 'هايتي | Haiti' },
  { value: 'HND', label: 'هندوراس | Honduras' },
  { value: 'HUN', label: 'هنغاريا | Hungary' },
  { value: 'ISL', label: 'آيسلندا | Iceland' },
  { value: 'IND', label: 'الهند | India' },
  { value: 'IDN', label: 'إندونيسيا | Indonesia' },
  { value: 'IRN', label: 'إيران | Iran' },
  { value: 'IRQ', label: 'العراق | Iraq' },
  { value: 'IRL', label: 'إيرلندا | Ireland' },
  { value: 'ITA', label: 'إيطاليا | Italy' },
  { value: 'JAM', label: 'جامايكا | Jamaica' },
  { value: 'JPN', label: 'اليابان | Japan' },
  { value: 'JOR', label: 'الأردن | Jordan' },
  { value: 'KAZ', label: 'كازاخستان | Kazakhstan' },
  { value: 'KEN', label: 'كينيا | Kenya' },
  { value: 'KIR', label: 'كيريباتي | Kiribati' },
  { value: 'KWT', label: 'الكويت | Kuwait' },
  { value: 'KGZ', label: 'قرغيزستان | Kyrgyzstan' },
  { value: 'LAO', label: 'لاوس | Laos' },
  { value: 'LVA', label: 'لاتفيا | Latvia' },
  { value: 'LBN', label: 'لبنان | Lebanon' },
  { value: 'LSO', label: 'ليسوتو | Lesotho' },
  { value: 'LBR', label: 'ليبيريا | Liberia' },
  { value: 'LBY', label: 'ليبيا | Libya' },
  { value: 'LIE', label: 'ليختنشتاين | Liechtenstein' },
  { value: 'LTU', label: 'ليتوانيا | Lithuania' },
  { value: 'LUX', label: 'لوكسمبورغ | Luxembourg' },
  { value: 'MKD', label: 'مقدونيا الشمالية | North Macedonia' },
  { value: 'MDG', label: 'مدغشقر | Madagascar' },
  { value: 'MWI', label: 'مالاوي | Malawi' },
  { value: 'MYS', label: 'ماليزيا | Malaysia' },
  { value: 'MDV', label: 'جزر المالديف | Maldives' },
  { value: 'MLI', label: 'مالي | Mali' },
  { value: 'MLT', label: 'مالطا | Malta' },
  { value: 'MHL', label: 'جزر مارشال | Marshall Islands' },
  { value: 'MRT', label: 'موريتانيا | Mauritania' },
  { value: 'MUS', label: 'موريشيوس | Mauritius' },
  { value: 'MEX', label: 'المكسيك | Mexico' },
  { value: 'FSM', label: 'ميكرونيزيا | Micronesia' },
  { value: 'MDA', label: 'مولدوفا | Moldova' },
  { value: 'MCO', label: 'موناكو | Monaco' },
  { value: 'MNG', label: 'منغوليا | Mongolia' },
  { value: 'MNE', label: 'الجبل الأسود | Montenegro' },
  { value: 'MAR', label: 'المغرب | Morocco' },
  { value: 'MOZ', label: 'موزمبيق | Mozambique' },
  { value: 'MMR', label: 'ميانمار | Myanmar' },
  { value: 'NAM', label: 'ناميبيا | Namibia' },
  { value: 'NRU', label: 'ناورو | Nauru' },
  { value: 'NPL', label: 'نيبال | Nepal' },
  { value: 'NLD', label: 'هولندا | Netherlands' },
  { value: 'NZL', label: 'نيوزيلندا | New Zealand' },
  { value: 'NIC', label: 'نيكاراغوا | Nicaragua' },
  { value: 'NER', label: 'النيجر | Niger' },
  { value: 'NGA', label: 'نيجيريا | Nigeria' },
  { value: 'PRK', label: 'كوريا الشمالية | North Korea' },
  { value: 'NOR', label: 'النرويج | Norway' },
  { value: 'OMN', label: 'عمان | Oman' },
  { value: 'PAK', label: 'باكستان | Pakistan' },
  { value: 'PLW', label: 'بالاو | Palau' },
  { value: 'PSE', label: 'فلسطين | Palestine' },
  { value: 'PAN', label: 'بنما | Panama' },
  { value: 'PNG', label: 'بابوا غينيا الجديدة | Papua New Guinea' },
  { value: 'PRY', label: 'باراغواي | Paraguay' },
  { value: 'PER', label: 'بيرو | Peru' },
  { value: 'PHL', label: 'الفلبين | Philippines' },
  { value: 'POL', label: 'بولندا | Poland' },
  { value: 'PRT', label: 'البرتغال | Portugal' },
  { value: 'QAT', label: 'قطر | Qatar' },
  { value: 'ROU', label: 'رومانيا | Romania' },
  { value: 'RUS', label: 'روسيا | Russia' },
  { value: 'RWA', label: 'رواندا | Rwanda' },
  { value: 'KNA', label: 'سانت كيتس ونيفيس | Saint Kitts and Nevis' },
  { value: 'LCA', label: 'سانت لوسيا | Saint Lucia' },
  { value: 'VCT', label: 'سانت فنسنت وجزر غرينادين | Saint Vincent and the Grenadines' },
  { value: 'WSM', label: 'ساموا | Samoa' },
  { value: 'SMR', label: 'سان مارينو | San Marino' },
  { value: 'STP', label: 'ساو تومي وبرينسيب | Sao Tome and Principe' },
  { value: 'SAU', label: 'المملكة العربية السعودية | Saudi Arabia' },
  { value: 'SEN', label: 'السنغال | Senegal' },
  { value: 'SRB', label: 'صربيا | Serbia' },
  { value: 'SYC', label: 'سيشيل | Seychelles' },
  { value: 'SLE', label: 'سيراليون | Sierra Leone' },
  { value: 'SGP', label: 'سنغافورة | Singapore' },
  { value: 'SVK', label: 'سلوفاكيا | Slovakia' },
  { value: 'SVN', label: 'سلوفينيا | Slovenia' },
  { value: 'SLB', label: 'جزر سليمان | Solomon Islands' },
  { value: 'SOM', label: 'الصومال | Somalia' },
  { value: 'ZAF', label: 'جنوب أفريقيا | South Africa' },
  { value: 'KOR', label: 'كوريا الجنوبية | South Korea' },
  { value: 'SSD', label: 'جنوب السودان | South Sudan' },
  { value: 'ESP', label: 'إسبانيا | Spain' },
  { value: 'LKA', label: 'سريلانكا | Sri Lanka' },
  { value: 'SDN', label: 'السودان | Sudan' },
  { value: 'SUR', label: 'سورينام | Suriname' },
  { value: 'SWE', label: 'السويد | Sweden' },
  { value: 'CHE', label: 'سويسرا | Switzerland' },
  { value: 'SYR', label: 'سوريا | Syria' },
  { value: 'TWN', label: 'تايوان | Taiwan' },
  { value: 'TJK', label: 'طاجيكستان | Tajikistan' },
  { value: 'TZA', label: 'تنزانيا | Tanzania' },
  { value: 'THA', label: 'تايلاند | Thailand' },
  { value: 'TLS', label: 'تيمور الشرقية | Timor-Leste' },
  { value: 'TGO', label: 'توغو | Togo' },
  { value: 'TON', label: 'تونغا | Tonga' },
  { value: 'TTO', label: 'ترينيداد وتوباغو | Trinidad and Tobago' },
  { value: 'TUN', label: 'تونس | Tunisia' },
  { value: 'TUR', label: 'تركيا | Turkey' },
  { value: 'TKM', label: 'تركمانستان | Turkmenistan' },
  { value: 'TUV', label: 'توفالو | Tuvalu' },
  { value: 'UGA', label: 'أوغندا | Uganda' },
  { value: 'UKR', label: 'أوكرانيا | Ukraine' },
  { value: 'GBR', label: 'المملكة المتحدة | United Kingdom' },
  { value: 'USA', label: 'الولايات المتحدة | United States' },
  { value: 'URY', label: 'أوروغواي | Uruguay' },
  { value: 'UZB', label: 'أوزبكستان | Uzbekistan' },
  { value: 'VUT', label: 'فانواتو | Vanuatu' },
  { value: 'VAT', label: 'الفاتيكان | Vatican City' },
  { value: 'VEN', label: 'فنزويلا | Venezuela' },
  { value: 'VNM', label: 'فيتنام | Vietnam' },
  { value: 'YEM', label: 'اليمن | Yemen' },
  { value: 'ZMB', label: 'زامبيا | Zambia' },
  { value: 'ZWE', label: 'زيمبابوي | Zimbabwe' }
];

export const MARITAL_STATUSES = [
  { value: 'single', label: 'أعزب/عزباء | Single' },
  { value: 'married', label: 'متزوج/متزوجة | Married' },
  { value: 'divorced', label: 'مطلق/مطلقة | Divorced' },
  { value: 'widowed', label: 'أرمل/أرملة | Widowed' },
  { value: 'other', label: 'أخرى | Other' },
];

export const DEGREES = [
  { value: 'none', label: 'لا يوجد مؤهل | No Qualification' },
  { value: 'primary', label: 'ابتدائي | Primary School' },
  { value: 'middle', label: 'إعدادي | Middle School' },
  { value: 'hs', label: 'ثانوية عامة | High School' },
  { value: 'ba', label: 'بكالوريوس | Bachelor' },
  { value: 'ma', label: 'ماجستير | Master' },
  { value: 'phd', label: 'دكتوراه | PhD' },
];

export const LICENSE_TYPES = [
  { value: 'private', label: 'رخصة خصوصي (خفيفة) | Private (Light)' },
  { value: 'heavy', label: 'رخصة ثقيلة | Heavy Vehicle' },
  { value: 'motorcycle', label: 'دراجة نارية | Motorcycle' },
  { value: 'bus', label: 'حافلة | Bus' },
  { value: 'none', label: 'لا يوجد | None' },
];

export const RELATIONSHIPS = [
  { value: 'parent', label: 'أب / أم | Parent' },
  { value: 'spouse', label: 'زوج / زوجة | Spouse' },
  { value: 'sibling', label: 'أخ / أخت | Sibling' },
  { value: 'friend', label: 'صديق | Friend' },
  { value: 'other', label: 'أخرى | Other' },
];